### ISSUE TITLE
Error starting web3py: pydal has no attribute 'validators'

### ISSUE THREAD

**Issue by advh67** [web2py/web3py#18]
Just downloaded files a few minutes ago. :

Traceback (most recent call last):
  File "web3py-start", line 6, in <module>
    main()
  File "****/web3py/core.py", line 706, in main
    args.password = pydal.validators.CRYPT()(getpass.getpass('Choose a one-time dashboad password: '))[0]
AttributeError: module 'pydal' has no attribute 'validators'

My pydal module is updated:
pip install pydal
Requirement already satisfied: pydal in /usr/lib/python3.7/site-packages (17.3)

By the way: thanks for web2py and web3py :-)

**Comment by advh67** [comment]
pydal has been updated a few seconds ago.
web2py starts nice now.

Sorry.
